allow-licenses:
  - 'Apache-1.1'
  - 'Apache-2.0'
  - 'MIT'
  - 'MIT-0'
  - 'MIT-Click'
  - 'MIT-CMU'
  - 'MIT-enna'
  - 'MIT-feh'
  - 'MIT-Festival'
  - 'MIT-Khronos-old'
  - 'MIT-Modern-Variant'
  - 'MIT-open-group'
  - 'MIT-testregex'
  - 'MIT-Wu'
  - 'BSD-1-Clause'
  - 'BSD-2-Clause'
  - 'BSD-2-Clause-first-lines'
  - 'BSD-2-Clause-Views'
  - 'BSD-3-Clause'
  - 'BSD-3-Clause-acpica'
  - 'BSD-3-Clause-Attribution'
  - 'BSD-3-Clause-Clear'
  - 'BSD-3-Clause-flex'
  - 'BSD-3-Clause-HP'
  - 'BSD-3-Clause-LBNL'
  - 'BSD-3-Clause-Modification'
  - 'BSD-3-Clause-No-Military-License'
  - 'BSD-3-Clause-No-Nuclear-License'
  - 'BSD-3-Clause-No-Nuclear-License-2014'
  - 'BSD-3-Clause-No-Nuclear-Warranty'
  - 'BSD-3-Clause-Open-MPI'
comment-summary-in-pr: on-failure